### ISSUE TITLE
Searched word and highlighted word are the same

### ISSUE THREAD

**Issue by Ivkaa** [Binaryify/OneDark-Pro#166]
When I want to rewrite something I searched for, when I select the area, the color of background highlight from searching is same as my highlighted part, which is very confusing, because I don't know what I highlighted. In this example I highlighted the argument in function.
![image](https://user-images.githubusercontent.com/16141183/33942013-e0b1ef2c-e014-11e7-8775-06005313dfff.png)

**Comment by darsain** [comment]
Also bugged me a lot (among other similar colors issues this theme has) so I did a bit of digging, and it seems to be a deeper issue upstream: https://github.com/Microsoft/vscode/issues/34105

But as suggested, even before it's solved it's still possible to add visual cues by using colors with transparency, since these selection/findMatch backgrounds are overlayed on top of each other.

**Comment by Binaryify** [comment]
I had improve it in the new version, please update and check it if it's better

**Comment by darsain** [comment]
Selection highlight is still indistinguishable from search highlight for me.

**Comment by Binaryify** [comment]
have not idea, do you have any advice @darsain

**Comment by darsain** [comment]
As explained in https://github.com/Microsoft/vscode/issues/34105, the problem here is that search highlight background is above selection highlight background, or maybe the other way around and they are the same colors, one of the two. Solution until this gets some better handling in vscode is using colors with alpha channel. That way even if 2 backgrounds are on top of each other they are still distinctive since the colors will "amplify" one another.

I don't have a specific color scheme to use here though. There is a lot of highlight variables in theming vscode. It'd require some playing around and tweaking.

**Comment by Binaryify** [comment]
@darsain 
if you have some good color scheme, could you let me know, and I will improve it

**Comment by LukasPolak** [comment]
hi, @Binaryify it is possible to make an options for example:
- editor.selectionHighlightBorder
- editor.wordHighlightBorder
- editor.findMatchHighlightBorder
- editor.findRangeHighlightBorder
- editor.lineHighlightBorder
- editor.rangeHighlightBorder

to see the difference for highlighting? thanks

**Comment by bsvipas** [comment]
@Ivkaa @darsain @LukasPolak @Binaryify created this issue: https://github.com/Binaryify/OneDark-Pro/issues/194 which will improve word highlighting after 1.21 version will be released. Stay tuned :)

**Comment by svipben** [comment]
Bad news, seems there's no such thing like `editor.selectionBorder` which is for selected text with mouse.

Good news I created issue in VS Code: https://github.com/Microsoft/vscode/issues/45292

**Comment by svipben** [comment]
Trying to push VS Code team to fix some border issues, even suggested making a PR. This issue will be definitely fixed. Stay tuned :)

**Comment by svipben** [comment]
@Ivkaa @LukasPolak @darsain I fixed this in my One Dark theme. I created it because I have a different vision and I want it to match Atom's One Dark as much as possible.

Repo: https://github.com/svipben/vscode-one-dark-theme
Theme: https://marketplace.visualstudio.com/items?itemName=svipben.one-dark
