### ISSUE TITLE
integrated terminal colors problem after 2.12.7

### ISSUE THREAD

**Issue by LukasPolak** [Binaryify/OneDark-Pro#195]
After update to version 2.12.7 I have a problem with integrated terminal colors

![integrated terminal colors problem](https://user-images.githubusercontent.com/17145302/37017717-e9c339de-2111-11e8-8fdc-2bf90f3e2304.png)

**Comment by mtobeiyf** [comment]
@LukasPolak  
Same problem. 
I checked, this only occurs in **powershell** that the color resembles the background.

Hope the author solve this. It's too hard to distinguish what I have input.
![image](https://user-images.githubusercontent.com/5097752/37018092-11ed14a2-214e-11e8-9571-af4bf0bb0e2d.png)
(There is a `-v` 😂

**Comment by Binaryify** [comment]
I just publish a new version, please update and check if it have been fix

**Comment by Binaryify** [comment]
@LukasPolak @mtobeiyf

**Comment by mtobeiyf** [comment]
@Binaryify  Much better. Thanks for the quick fix.
![image](https://user-images.githubusercontent.com/5097752/37019030-9a348fd6-2151-11e8-954a-ab1c2590ccd8.png)

**Comment by PixelT** [comment]
For me it's still broken, I had white font color, now I have as `-v` on image above...

**Comment by Binaryify** [comment]
@PixelT could you provide some screenshot?

**Comment by PixelT** [comment]
@Binaryify

![](https://i.imgur.com/UAE3WnU.png)

Earlier I had white text color on this blue & green elements

**Comment by Binaryify** [comment]
so you want it be pure white right?

**Comment by Or3stis** [comment]
This issue may depend on the local configuration of your terminal colors. If your default terminal colors are light theme based (white background), then some colors will not be displayed currently using this theme (dark background).

@PixelT, @LukasPolak can you share your terminal color configuration of your `.bash_profile` so we can test this?

**Comment by Binaryify** [comment]
@Or3stis 
maybe it should be more light

**Comment by svipben** [comment]
I suggest returning back as it was. Just delete the terminal coloring and keep to default as it was before.

**Comment by Or3stis** [comment]
@svipben why?

With the updated colors, the terminal looks more consistent with the rest of the color theme.

I would prefer to investigate the issue. If it affects only all PowerShell users or a portion of PowerShell there might be an issue with their configuration. I have been using that color scheme for a couple of weeks before I made the PR without any issue.

As I said, it seems odd that the `terminal.ansiBrightBlack` color needs a white color value to display text.

**Comment by svipben** [comment]
![image](https://user-images.githubusercontent.com/10441177/37254613-bce238f8-2548-11e8-91ed-8cbcfb19ca14.png)

I never had such issues with default terminal coloring which looked perfect.

For me the `"terminal.ansiWhite"` is bad.

**Comment by Or3stis** [comment]
I see what you mean.

It is best to revert the changes then.

I will keep the updated colors in my settings to test them further.

**Comment by svipben** [comment]
@Or3stis I will create PR which removes terminal coloring and keeps it as it was by default. Anyways thanks for contributing for this theme, try to test all possible cases and when you think it will be ready you can create new PR which can be reviewed. But my suggestion is to keep it always as default to reduce problems like this and keep original coloring since it's terminal, no the editor itself.

**Comment by svipben** [comment]
Done in this PR: https://github.com/Binaryify/OneDark-Pro/pull/205

**Comment by adrigm** [comment]
I used this theme because this was the only One Dark theme for VS Code that changed the integrate terminal colors.

**Comment by svipben** [comment]
@adrigm If you're only one who chooses this theme because of integrated terminal coloring you can easily edit your User Settings to include your own coloring for the integrated terminal. But if there are more people like you we should consider about new theme especially with terminal coloring like it's with Vivid.

https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by svipben** [comment]
Okay I tested and without terminal coloring, there are some problems, for e.g. with yellow in the integrated terminal because of our foreground which is not white. So I included the fix in this PR https://github.com/Binaryify/OneDark-Pro/pull/206. I reverted back @Binaryify terminal colors like it was before. I also improved a little bit green color to not be so bright.

This will be our first steps to perfect integrated terminal coloring.

@adrigm You can use again this theme 😄

**Comment by svipben** [comment]
@adrigm PR was merged so you will have terminal coloring again, of course not the full, but the critical parts which were not consistent with the theme itself will be fixed.

Thanks, @Binaryify for merging it!

I guess @LukasPolak this issue can be closed?

**Comment by LukasPolak** [comment]
@Binaryify @svipben I think that issue can be closed
