### ISSUE TITLE
Angular Syntax Highlighting?

### ISSUE THREAD

**Issue by dertuerke** [Binaryify/OneDark-Pro#200]
Hi, it is possible to highlight the values inside the {{ }}?

VSCode 1.21
![image](https://user-images.githubusercontent.com/2199151/37136769-47664aa8-22a3-11e8-8cf3-9a2f41c45993.png)

VSCode Inside
![image](https://user-images.githubusercontent.com/2199151/37136790-5bd092f0-22a3-11e8-8f2f-2b3a1044200d.png)

**Comment by Binaryify** [comment]
hard to support it now
![image](https://user-images.githubusercontent.com/12221718/37137865-b5f64be6-22e2-11e8-8f3a-abd4b7f1713d.png)

**Comment by dertuerke** [comment]
Ow ok.
But, why does it work with the Inside build?

**Comment by Binaryify** [comment]
maybe Inside version make their scope more special

**Comment by svipben** [comment]
@dertuerke can you show VS Code Insiders scope with CMD + SHIFT + P using Developer: Inspect TM Scopes?

**Comment by dertuerke** [comment]
![image](https://user-images.githubusercontent.com/2199151/37139286-a43192ce-22ad-11e8-8507-1b8fe42d2223.png)

![image](https://user-images.githubusercontent.com/2199151/37139296-af981390-22ad-11e8-8bce-2c6c72e8a898.png)

**Comment by svipben** [comment]
@dertuerke can you add your cursor on `produce.list` in the middle and do the same? To see what scope of text it's instead of punctuation.

**Comment by dertuerke** [comment]
@svipben so?

![image](https://user-images.githubusercontent.com/2199151/37139594-c63faf1c-22ae-11e8-8036-d15101714e9c.png)

**Comment by svipben** [comment]
Yeah seems Insiders build have better scopes. Can you create an issue in VS Code GitHub repo and point to this issue since this isn't theme problem because it's impossible to create coloring if there are no supported scopes. And the last question do you use exactly the same extensions on 1.21 like Insiders?

**Comment by dertuerke** [comment]
@svipben thx firstly :)

I look once time to my extensions and i found that this extension make the highlighting

https://marketplace.visualstudio.com/items?itemName=mblode.twig-language

**Comment by svipben** [comment]
@Binaryify Seems @dertuerke was having extension which introduced these new scopes. So this impossible to fix since this is VS Code related. @dertuerke you can open issue in VS Code repo.

**Comment by dertuerke** [comment]
That is not a issue from VS Code :S

If i install the extension on VS 1.21 i see the same Highlight

**Comment by svipben** [comment]
@dertuerke Seems it's issue from VS Code side because only with that extension you see coloring. They need to improve current scopes to handle it better which will add the ability for us to create coloring for this. As I said open issue in VS Code and add a reference to this issue too. As a workaround use that extension to get coloring.

**Comment by svipben** [comment]
@dertuerke I guess this issue can be closed since this isn't the problem with the theme itself, but with the VS Code? Also, did you opened an issue in VS Code repo about this?
