### ISSUE TITLE
Broken border styles and highlighting.

### ISSUE THREAD

**Issue by MilyMilo** [Binaryify/OneDark-Pro#203]
With VS Code 1.21 on Ubuntu, border highlighting is broken.

This is how it looks, Monokai on the other hand works just fine.

![One](https://user-images.githubusercontent.com/24303006/37252957-61f09df8-252b-11e8-9311-0ddd2081ad7f.png)
![Two](https://user-images.githubusercontent.com/24303006/37252958-620e41aa-252b-11e8-9d7e-1644cacab4f8.png)

Microsoft/vscode#45479

**Comment by svipben** [comment]
This feature was introduced in VS Code 1.21 (https://code.visualstudio.com/updates/v1_21#_new-theme-colors-and-removal-of-old-colors).

Monokai theme doesn't have these because it doesn't have borders specified in theme.

So this problem isn't specific to OS or any other theme this is because VS Code currently shows border dotted instead of straight lines.

I created PR to border values because this helps a lot, especially in large files. I already created issue about this: https://github.com/Microsoft/vscode/issues/45479 which have your comments since you misunderstood about what I'm talking...

**Comment by svipben** [comment]
@MilyMilo since this is the problem with the VS Code itself because border style isn't straight lines but dots I believe this issue can be closed?

**Comment by svipben** [comment]
Trying to push VS Code team to fix this issue to get proper border style instead of dots. Even suggested making a PR. Stay tuned :)

**Comment by xixixao** [comment]
I don't want any border around the selection, so this is the workaround (assuming one dark syntax theme) (put this in user settings):
```js
"workbench.colorCustomizations": {
  "editor.selectionHighlightBorder": "#333A46",
},
```
