### ISSUE TITLE
Inconsistant color in Js Objects.

### ISSUE THREAD

**Issue by FilipAndersson245** [Binaryify/OneDark-Pro#233]
The color is inconsistent when you are using a method inside a JavaScript Object.
If its on one line its blue but it spawn multiple lines its red like the normal props.

**Comment by beastdestroyer** [comment]
Has been fixed, ready to close

**Comment by beastdestroyer** [comment]
Before I start, I'm not sure what you mean by `using a method insider a JavaScript Object`, I have thought of 4 possible meanings, but feel free to correct me.

The first 3 methods:
```js
let methods = {
  es5Func: function test1() { 
    return true;
    },
  es6Meth() {
    return true;
  },
  arrow: () => true;
}
```

all work for me. For evidential proof (using One Dark Pro Vivid 2.17.4)
![image](https://user-images.githubusercontent.com/30497573/47426740-0092a480-d786-11e8-99af-ab17eb188fa5.png)


However this won't work correctly:
```js
let methods = {
  fails: lol()
}

function lol() { //even declared the function, doesn't work!!!
  console.log("lol");
}
```

The main reason why this doesn't highlight to your taste is because what you're doing is PASSING BY REFERENCE. It actually means that syntax highlighting is correct because you're not explicitly calling `lol()`, you're referring to `methods.fail`, which in turn will call the lol function. As such, you're not actually turning `methods.fail` into `methods.fail()`, otherwise it would turn blue.


It even shows up in GitHub flavoured too
Hope this helps!

**Comment by beastdestroyer** [comment]
@Binaryify Good to close
