### ISSUE TITLE
Javascript: some methods are green, other blue

### ISSUE THREAD

**Issue by ivanbeldad** [Binaryify/OneDark-Pro#260]
Just installed this extension and notice that only some methods are green.

![image](https://user-images.githubusercontent.com/10326536/46250028-3ff1fd80-c433-11e8-9856-18a226b34917.png)

This only happens to methods, no functions.

![image](https://user-images.githubusercontent.com/10326536/46250101-fbb32d00-c433-11e8-942f-d585c32ac33b.png)

![image](https://user-images.githubusercontent.com/10326536/46250105-08378580-c434-11e8-8f15-807492b46048.png)

**Comment by jens1o** [comment]
The green ones are when the grammar detects built-in methods of javascript modules.

**Comment by ivanbeldad** [comment]
But map is a built-in method too, that's why I used it for the example, because I didn't find a logic relation between colors. There are a lot of built-in methods in blue.

Is there a property to change them all to the same color? Thank you.

**Comment by beastdestroyer** [comment]
Yup, copy and paste the following code into your `settings.json`:

```json
{
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "entity.name.function.js",
        "settings": {
          "foreground": "#2BBAC5"
        }
      }
    ]
  }
}
```
This is assuming that you want both in-built and custom functions/methods to all be that greenish colour. The reason they are different is because VSCode identifies them as the same type of grammar: `entity.name.function`, and changing this will also change the colours of your own-defined functions. If you really want this I recommend opening an issue against VSCode's grammar service (probs in one of their Language Service Providers or whatever nonsense they call them now), otherwise there really isn't much we can do other than colours @Binaryify

**Comment by ivanbeldad** [comment]
I assumed that it wasn't a problem with One Dark, but didn't know exactly what was the source, so I opened the issue here.

Thanks @beastdestroyer for the tip. I'll close this issue.

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/46267027-79c32100-c565-11e8-8a9e-f7473ca04b61.png)
![image](https://user-images.githubusercontent.com/12221718/46267028-7e87d500-c565-11e8-9ca8-f879813a2497.png)
well, that is vscode's problem, they have different scope

**Comment by beastdestroyer** [comment]
Np :)
