### ISSUE TITLE
Inconsistency for Ruby 1.9 symbol

### ISSUE THREAD

**Issue by foreverqihe** [Binaryify/OneDark-Pro#268]
Thank you for solving the ruby color for symbol.
It would be great if you can do one more change for an alternative symbol syntax for Ruby 1.9+
```ruby
:one => 1 # normal form

one: 1 # ruby 1.9+
```
So it is still inconsistent. And even the function args look different as well:)
Atom:![image](https://user-images.githubusercontent.com/2378002/46580640-70115000-ca74-11e8-8ace-434a6899a72f.png)

One Dark Pro:
![image](https://user-images.githubusercontent.com/2378002/46580647-90410f00-ca74-11e8-8f57-4f000a69e5fc.png)

_Originally posted by @foreverqihe in https://github.com/Binaryify/OneDark-Pro/issues/258#issuecomment-427642264_

**Comment by foreverqihe** [comment]
> I cannot repro this as per this screenshot (I have no idea how to Ruby),
> ![image](https://user-images.githubusercontent.com/30497573/47426350-d7bddf80-d784-11e8-8ed9-a7bf0cdc436c.png)
> 
> What version of VSCode and One Dark Pro are you using?

I am using vs code 1.28.2 and Ruby plugin 0.20.0. One Dark Pro 2.17.4

Maybe you didn't install the plugin but it is necessary for a Ruby developer. To replicate, create a file ends with ".rb", e..g test.rb and paste the code into it. Open it with vs code.

**Comment by beastdestroyer** [comment]
Alright I get it now. Thanks for the help.

When installing the Ruby extension on VSCode, it creates additional scopes that native VSCode does not have. Of these scopes which are relevant to your issue, are: `variable` and `constant`. Since One Dark Pro only really supports the languages' prebuilt scopes (and Ruby never provided them in the first place), the default highlighting for these scopes will just come into effect. As such the default `variable` is that red colour and the default `constant` is that yellowish-orange.

Now I haven't investigated Atom completely, but it seems the Ruby language doesn't define those `variable` and `constant` scopes like VSCode, hence it uses that highlighting shown in your first screenshot. You might then suggest to incorporate this change but that'd be up to @Binaryify as it is extension-related rather than prebuilt. You could always fork and open a pull request, or I could... Either is fine, but he has the final say :>

Hope this helps!

**Comment by beastdestroyer** [comment]
You could also just define them in your settings.json too...
