### ISSUE TITLE
Support keyword.operator for C++

### ISSUE THREAD

**Issue by JayXon** [Binaryify/OneDark-Pro#286]
When using the [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension, it correctly labels the operators in C++, this works for various other themes but the operators lost color when using this theme.

Details at https://github.com/jeff-hykin/cpp-textmate-grammar/issues/7

**Comment by jeff-hykin** [comment]
VS Code just switched their grammar to pull from the Better C++ Syntax extension https://github.com/Microsoft/vscode/issues/68392#event-2177440780
So this now might be a higher priority issue since most operators are currently colored white.

<img width="292" alt="screen shot 2019-03-04 at 10 48 08 am" src="https://user-images.githubusercontent.com/17692058/53748581-3732a700-3e6b-11e9-8ae5-399e6c096a0b.png">

**Comment by Binaryify** [comment]
@JayXon @jeff-hykin 
you can check it now

**Comment by JayXon** [comment]
Still no color on 2.19.1, wrong commit? 5f9bf4c only changed version number

**Comment by Binaryify** [comment]
@JayXon sorry for that, my Mac and my PC project didn't sync

**Comment by Binaryify** [comment]
the separator should have right highlight now

**Comment by jeff-hykin** [comment]
Verified working on my end. Thanks 👍
