### ISSUE TITLE
Background colour inconsistencies

### ISSUE THREAD

**Issue by Genora51** [Binaryify/OneDark-Pro#347]
![Screenshot 2019-11-08 at 17 44 42](https://user-images.githubusercontent.com/19515086/68498711-76fa2b80-024f-11ea-8832-2c2f73ca04a5.png)

Notice how the bottom third of the screenshot is very slightly lighter (`#282c34` according to my mac's digital colour meter) than the main background (`#282b34`). Not sure why this is.

**Comment by Binaryify** [comment]
Will this happen after you restart vscode?

**Comment by Genora51** [comment]
Restarting vscode doesn't seem to fix the issue.

**Comment by mskelton** [comment]
@Genora51 The background color is consistent throughout the entire page according to VS Code dev tools.  My guess is that this is just an issue with the mac color meter not reading it correctly.

**Comment by Binaryify** [comment]
that might be vscode 's itself issue

**Comment by WilSnoop** [comment]
@Binaryify: The issue is on Electron. Strangely only some PCs show this problem. It has to do with colour calibration and the influence thereof.

@mskelton: The picture by @Genora51 does have some colour change. Look again at magnification and note a lighter block at bottom right. A small piece of darker colour remains on the left bottom side.

Please follow the picture below. Look into what the setting does (also follow the link) and what it does for you. Please update us if it makes a change or not.

![image](https://user-images.githubusercontent.com/57892121/69641748-6cba9880-1069-11ea-8300-dd0e13da54f3.png)

**Comment by mskelton** [comment]
@WilSnoop Thanks for the detailed response and the correction of my mistake.  I now can see what you are referring to and feel bad for not noticing it earlier.  Great find with the setting that can be used to fix it!

**Comment by WilSnoop** [comment]
@mskelton: No worries friend. 
We do not know if what I posted is helpful until @Genora51 confirms so.

**Comment by Genora51** [comment]
Oddly enough, the issue seems to have resolved itself! I'm not sure if it's the newest update but I'm going to close the issue for now since it no longer seems to be a problem. If it does reappear I'll try the suggested solution and reopen the issue.

Thanks for all your help :)
