### ISSUE TITLE
JavaScript operator coloring

### ISSUE THREAD

**Issue by nnooney** [Binaryify/OneDark-Pro#407]
In this snippet of JavaScript code, I would expect the assignment operator (=) and the compound assignment operator (+=) to have the same syntax highlighting.

![image](https://user-images.githubusercontent.com/3597640/87001642-c7be7d00-c16c-11ea-9a7b-423810432b64.png)

Should these be consistent?

**Comment by cotneit** [comment]
Totally agree. It seems to be a bug since that's how it works in Python.
-=, +=, *=, %= are purple in JS.

What weird is that \= is not and is treated as 2 separate operators instead of one compound:
![image](https://user-images.githubusercontent.com/36513243/87874385-18866f00-c9d2-11ea-8877-c1aca99680b5.png)

But if you make a typo and place some operator in front of them, they are treated as one:
![image](https://user-images.githubusercontent.com/36513243/87874505-0d800e80-c9d3-11ea-8f4f-d19926498f20.png)
