### ISSUE TITLE
Python semantic highlithing is broken

### ISSUE THREAD

**Issue by MalcolmMielle** [Binaryify/OneDark-Pro#439]
Hi,

Thanks for the beautiful theme. However, python semantic highlighting seems broken. When I turn it on with 

      "editor.semanticHighlighting.enabled": true,

Everything turns red: variable, function arguments...

**Comment by HymanZHAN** [comment]
For comparison:

- Before (more or less):
![Screenshot from 2020-09-07 22-40-53](https://user-images.githubusercontent.com/26806995/92427765-4cbd1700-f15b-11ea-835c-df8031b9281e.png)

- Now:
![Screenshot from 2020-09-07 22-40-43](https://user-images.githubusercontent.com/26806995/92427755-46c73600-f15b-11ea-856e-f67d8cd93c45.png)

Is this intentional?

**Comment by akanz1** [comment]
Same issue here. I doubt that it is intentional since everything is colored now and the changelog doesn't mention anything in that direction.

**Comment by neverrop** [comment]
got the same trouble, any fix now?

**Comment by LampV** [comment]
Hello, I have the same problem, and I'm using `pylance` as my language server, which is recommended by Microsoft and VSCode.  
I think it is pylance's fault, it gives one-dark-pro wrong word type.   
For example, `self` in python is defined in 
```json
{
  "name": "variable.parameter.function.language.special.self.python",
  "scope": "variable.parameter.function.language.special.self.python",
  "settings": {
    "foreground": "#e5c07b"
  }
},
```
but the type of `self` is `Variables`and color is `#ef596f`(red) in practice.  
This can be proved by changing color of `Variables` to `#efff33`, which is highlight yellow. It looks like:  
- before:  
![截屏2020-09-08 下午4 36 32](https://user-images.githubusercontent.com/38694199/92453141-7d4f9000-f1f1-11ea-890a-e259815f70cb.png)
- after:  
![截屏2020-09-08 下午4 20 33](https://user-images.githubusercontent.com/38694199/92453168-85a7cb00-f1f1-11ea-8b3a-b9615c098df7.png)

So I believe it's because the language server is passing the wrong word type to the theme. And when I disabled pylance, the theme was back to normal.

**Comment by mgresko** [comment]
https://github.com/microsoft/pylance-release/issues/339

Basically the fix is:

```
{
    "[python]": {
        "editor.semanticHighlighting.enabled": false
    }
}
```

**Comment by MalcolmMielle** [comment]
Isn't that just disabling semantic highlighting instead of fixing this issue? I don't know if one Dark is supposed to support semantic highlithing :)

**Comment by Binaryify** [comment]
@MalcolmMielle support that will make many broken, semanticHighlighting don't support language scope, if I support that, all other language's variable will lose highlight

**Comment by jakebailey** [comment]
We added semantic highlighting support to Pylance by declaring support and returning tokens to the editor; we did so with the tokens standardized by the language server protocol, but is it more common for languages to be declaring their own specialized tokens, e.g. "hey, this is `self`, color it differently"? It seems like that'd mean every theme would have to define everything for every language, rather than relying on the standard tokens.

**Comment by Binaryify** [comment]
v3.10.9 had already fixed this, thank for I can add the language in the rule matcher
![image](https://user-images.githubusercontent.com/12221718/113513289-98258f80-959b-11eb-8249-b5925e3d199d.png)

**Comment by jakebailey** [comment]
I think the color choices are a bit wrong' the colors that have been added are now inconsistent with the other langauge's variable colors. Previously, they were consistent with other languages.

I know the intent was to make this configurable, but I believe that the defaults should remain as they were before (and in other languages), not this "gray" color that only existed in VS Code by default because the TextMate profile didn't know how to handle variables and gave them the "unknown" (gray) type.

**Comment by jakebailey** [comment]
FWIW now we're getting reports on Pylance that things broke (hence me commenting here; this is the theme we use ourselves and show off in screenshots and such as it has the best colorization support), because the new colorization is unexpected: https://github.com/microsoft/pylance-release/issues/1127

**Comment by jakebailey** [comment]
Actually, I'm not sure what the intent was; Pylance did already return tokens of variable/parameter types and they were colored via the existing rules. What do these new rules get other than emulating the old (inconsistent) VS Code color choices?

The original issue was "everything turns red", but that's just how the theme looks in other languages. I don't think this issue really needed a fix if it aimed to be consistent with the other languages it colors, but that's my opinion.

**Comment by Binaryify** [comment]
@jakebailey will reverting the changes soon

**Comment by Binaryify** [comment]
@jakebailey v3.10.10 had already fix this problem, please confirm and I will close this issue

**Comment by jakebailey** [comment]
Yes, things have returned to their original state now. Thank you!
