### ISSUE TITLE
Golang's color scheme supports different constants and variables

### ISSUE THREAD

**Issue by zweix123** [Binaryify/OneDark-Pro#822]
**Describe what you want**

Golang's color scheme supports different constants and variables

**Additional context**

For the following code

```go
package main

import "fmt"

func f(s string) {
	fmt.Println(s)
}

func main() {
	v := "123"
	const c = "123"
	f(v)
	f(c)
}
```

The effect in Goland is
![b554ccd97bf790a22271962327437695](https://github.com/user-attachments/assets/89a94389-53d5-4f91-b930-8c4fd07591ed)

But using the OneDark theme on VSCode is
<img width="227" alt="c340df3f81c5b49f29a07e71061dc0e8" src="https://github.com/user-attachments/assets/f521ba1e-0916-42a7-a195-9ca680aa2ae5">

Cannot recognize constants and variables and assign different color schemes.

**Comment by zhuchengrui-acathe** [comment]
This is not an issue with the theme. it’s because the VS Code Go extension does not support this type of highlighting.

Adding the following configuration should resolve the issue:
```json
{
    "gopls": {
        "ui.noSemanticNumber": true,
        "ui.noSemanticString": true,
        "ui.semanticTokens": true
    }
}
```

<img width="284" alt="截屏2024-12-24 19 45 26" src="https://github.com/user-attachments/assets/5cfe8e00-812c-48e9-9356-bb64087b8bd3" />

For reference, see [vscode-go issue #2751](https://github.com/golang/vscode-go/issues/2752).

**Comment by zweix123** [comment]
Understood, thank you very much.

**Comment by zweix123** [comment]
Understood, thank you very much.
